import base64
import cv2
from fastapi import APIRouter, Response
from fastapi.responses import StreamingResponse
from yolo_detector import detector_instance

router = APIRouter(prefix="/api/camera", tags=["YOLO Live Camera Stream"])

@router.get("/stream")
def video_feed():
    """
    Returns an MJPEG stream generated by the YOLO OpenCV Computer Vision model.
    """
    return StreamingResponse(
        detector_instance.generate_mjpeg_stream(),
        media_type="multipart/x-mixed-replace; boundary=frame"
    )

import time

_cached_frame_bytes = None
_last_frame_time = 0.0

@router.get("/frame")
def get_single_frame():
    """
    Returns a single JPEG frame byte response for dynamic cross-platform streaming with 100ms caching.
    """
    global _cached_frame_bytes, _last_frame_time
    now = time.time()
    if _cached_frame_bytes is not None and (now - _last_frame_time) < 0.1:
        return Response(
            content=_cached_frame_bytes,
            media_type="image/jpeg",
            headers={"Cache-Control": "no-cache, no-store, must-revalidate"}
        )

    frame = detector_instance.generate_frame()
    ret, jpeg = cv2.imencode('.jpg', frame, [cv2.IMWRITE_JPEG_QUALITY, 75])
    if not ret:
        return Response(status_code=500)

    _cached_frame_bytes = jpeg.tobytes()
    _last_frame_time = now
    return Response(
        content=_cached_frame_bytes,
        media_type="image/jpeg",
        headers={"Cache-Control": "no-cache, no-store, must-revalidate"}
    )

@router.get("/status")
def get_camera_status():
    return {
        "camera_id": "CAM-01-NORTH",
        "resolution": "1080p",
        "fps": 30,
        "status": "ONLINE",
        "ai_model": "YOLOv8-Parking-ROI",
        "detected_slots": detector_instance.get_slot_states()
    }
